import { useEffect, useState } from 'react';
import Head from 'next/head';

import 'devtools-detect';

import { FirstBlock, MemoizedFirstBlock } from '../components/Block';
import Dialog from '../components/Dialog';
import Footer from '../components/Footer';
import Header from '../components/Header';

export default function Layout({ children }) {
  const [devtoolStatus, setDevtoolStatus] = useState(false);

  const handleDevtoolDetect = (event) => {
    if (
      !/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)
    ) {
      setDevtoolStatus(event.detail.isOpen);
    }
  };

  useEffect(() => {
    window.addEventListener('devtoolschange', handleDevtoolDetect);
    return () => {
      window.removeEventListener('devtoolschange', handleDevtoolDetect);
    };
  }, []);

  return (
    <div
      className={`${
        devtoolStatus ? 'flex' : ''
      } max-w-screen min-h-screen bg-gray-100`}
    >
      <Head>
        <title>Nam Nguyen</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,700&amp;display=swap"
        />
        <meta property="og:type" content="website" />
        <link href="/favicon.ico" rel="icon" type="image/x-icon" />
      </Head>
      {!devtoolStatus && (
        <>
          <Header />
          {children}
          <Footer />
          <Dialog />
        </>
      )}
      {devtoolStatus && <MemoizedFirstBlock />}
    </div>
  );
}
