import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nam Nguyen</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital@0;1&amp;display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="absolute top-10 right-0 mr-5 flex gap-x-4">
        <a href="https://github.com/Hnamnguyen0112" rel="noreferrer" target="_blank">
          <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"
               shapeRendering="geometricPrecision" viewBox="0 0 24 24" className="contact" height="28" width="28"
               style={{ color: '#fff' }}>
            <path
              d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 00-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0020 4.77 5.07 5.07 0 0019.91 1S18.73.65 16 2.48a13.38 13.38 0 00-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 005 4.77a5.44 5.44 0 00-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 009 18.13V22" />
          </svg>
        </a>
        <a href="https://www.linkedin.com/in/namnguyen0112/" rel="noreferrer" target="_blank">
          <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"
               shapeRendering="geometricPrecision" viewBox="0 0 24 24" className="contact" height="28" width="28"
               style={{ color: '#fff' }}>
            <path d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z" />
            <circle cx="4" cy="4" r="2" />
          </svg>
        </a>
        <a href="https://twitter.com/_alexnguyennn" rel="noreferrer" target="_blank">
          <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"
               shapeRendering="geometricPrecision" viewBox="0 0 24 24" className="contact" height="28" width="28"
               style={{ color: '#fff' }}>
            <path
              d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z" />
          </svg>
        </a>
        <a href="mailto:alexnguyenth96@gmail.com" rel="noreferrer" target="_blank">
          <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"
               shapeRendering="geometricPrecision" viewBox="0 0 24 24" className="contact" height="28" width="28"
               style={{ color: '#fff' }}>
            <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />
            <path d="M22 6l-10 7L2 6" />
          </svg>
        </a>
      </div>

      <div className="max-w-xl mx-auto">
        <h1 className={'text-8xl font-bold text-black'}>
          <span className={styles.underline}>Nam Nguyen</span>
        </h1>
        <p className="mt-10 text-xl">
          <br />
          <span className="text-3xl font-semibold">
          👋 Hey! I&apos;m Nam, but you can call me Alex
        </span>
          <br /><br />
          nice to meet you btw!
          <br />
          ...I&apos;m building diverse & highly accessible applications for everyone,
          <br />
          also working as a Software Engineer in Vietnam
          <br />
          who&apos;s got experience in <code className="text-cyan-500">PHP</code>, <code
          className="text-amber-300">Javascript</code> and <code className="text-emerald-300">Go</code>.
          <br />
          This is a small landing page I put together.
          <br /> <br />
          Thanks for coming by!
        </p>
      </div>
    </div>
  )
}
